"""empty message

Revision ID: 41e5419523b
Revises: None
Create Date: 2016-06-11 21:34:44.651345

"""

# revision identifiers, used by Alembic.
revision = '41e5419523b'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('staff__member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=25), nullable=True),
    sa.Column('last_name', sa.String(length=30), nullable=True),
    sa.Column('team', sa.String(length=40), nullable=True),
    sa.Column('manager', sa.String(length=55), nullable=True),
    sa.Column('team_lead', sa.String(length=55), nullable=True),
    sa.Column('role', sa.String(length=60), nullable=True),
    sa.Column('extension', sa.String(length=6), nullable=True),
    sa.Column('phone_number', sa.String(length=14), nullable=True),
    sa.Column('location', sa.String(length=60), nullable=True),
    sa.Column('active_regions', sa.String(length=200), nullable=True),
    sa.Column('office_hours', sa.String(length=200), nullable=True),
    sa.Column('duties', sa.String(length=600), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=15), nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=True),
    sa.Column('profile_image_uri', sa.String(length=200), nullable=True),
    sa.Column('profile_thumb_uri', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['staff_id'], ['staff__member.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('staff__member')
    ### end Alembic commands ###
